# =============================================================
#  Fail2ban — filter.d/suricata.conf
#  Filtro personalizado para leer el fast.log de Suricata
#  Proyecto Integrado ASIR — César Acevedo Gomez
#  IES Fuengirola 1 — 2025/2026
# =============================================================

[Definition]
datepattern = %%m/%%d/%%Y-%%H:%%M:%%S.%%f

failregex = ^\s*\[\*\*\]\s+.*\[\*\*\].*\{.*\}\s+<HOST>:\d+\s+->\s+.*$

ignoreregex =
